name: Deploy Backend with Spring Boot to AWS EC2

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: "temurin"
          java-version: "11"
          cache: maven
          settings-path: "Proyecto_Integrador/ProyectoIntegrador/*"
      - name: Build Project
        run: cd Proyecto_Integrador/ProyectoIntegrador && mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u pabloc43 -p 123456789
      - name: Build docker image
        run: docker build -t pabloc43/proyecto_integrador:latest Proyecto_Integrador/ProyectoIntegrador/.
      - name: Publish image to docker hub
        run: docker push pabloc43/proyecto_integrador:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Login to docker hub
        run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Pull Image from docker hub
        run: sudo docker pull aguekdjian/backend-java:latest
      - name: Delete old container
        run: sudo docker rm -f backend-java-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name backend-java-container -e DB_URL=${{secrets.DB_URL}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e DB_UPDATE=${{secrets.DB_UPDATE}} aguekdjian/backend-java:latest
