name: Java CI with Maven and EC2 Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file Proyecto_Integrador/pom/pom.xml

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "Proyecto_Integrador/target/your-application.jar"  # Actualiza con el nombre correcto del JAR
        target: "/ruta/en/la/instancia/tu_aplicacion"  # Ruta en la instancia donde deseas colocar el JAR

    - name: SSH into EC2 and Restart Application
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /ruta/en/la/instancia/tu_aplicacion && nohup java -jar your-application.jar > output.log 2>&1 &"  # Actualiza con el nombre correcto del JAR

