name: Deploy Backend with Spring Boot to AWS EC2

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: "temurin"
          java-version: "11"
          cache: maven
          settings-path: "Proyecto_Integrador/ProyectoIntegrador/*"
      - name: Build Project
        run: cd Proyecto_Integrador/ProyectoIntegrador && mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u pabloc43 -p 123456789
      - name: Build docker image
        run: docker build -t pabloc43/proyecto_integrador:latest Proyecto_Integrador/ProyectoIntegrador/.
      - name: Publish image to docker hub
        run: docker push pabloc43/proyecto_integrador:latest

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        run: docker login -u pabloc43 -p 123456789

      - name: Pull Image from Docker Hub
        run: docker pull pabloc43/proyecto_integrador:latest

      - name: Delete old container
        run: docker rm -f proyecto_integrador || true

      - name: Run Docker container
        run: docker run -d -p 8081:8081 --name proyecto_integrador pabloc43/proyecto_integrador:latest

